run:
	pip install pydub 
	pip install openai-whisper 
	pip install opencv-python
	pip install -U openai-whisper 
	pip install git+https://github.com/openai/whisper.git 
	pip install --upgrade --no-deps --force-reinstall git+https://github.com/openai/whisper.git 
	pip install moviepy 
	pip install pypdf2 
	pip install numpy 
	python3 main.py
clean:
	rm -f *.tsv
	rm -f *.srt
	rm -f *.json
	rm -f *.vtt
	rm -f temp.mp4
	rm -f temp.wav
	
	